# edgenet drops

language: c

#   Build required ZeroMQ projects first
before_script:
- sudo apt-get -qq update
- sudo apt-get install uuid-dev

#   libsodium
- git clone git://github.com/jedisct1/libsodium.git
- cd libsodium
- ./autogen.sh && ./configure && make check
- sudo make install && sudo ldconfig
- cd ..

#   libzmq
- git clone git://github.com/zeromq/libzmq.git
- cd libzmq
- ./autogen.sh && ./configure && make check
- sudo make install && sudo ldconfig
- cd ..

#   CZMQ
- git clone git://github.com/zeromq/czmq.git
- cd czmq
- ./autogen.sh && ./configure && make check
- sudo make install && sudo ldconfig
- cd ..

#   Zyre
- git clone git://github.com/zeromq/zyre.git
- cd zyre
- ./autogen.sh && ./configure && make check
- sudo make install && sudo ldconfig
- cd ..

#   Android build tools
- sudo apt-get install libstdc++6:i386 libgcc1:i386 zlib1g:i386 libncurses5:i386 ant
- wget http://dl.google.com/android/android-sdk_r22.3-linux.tgz
- tar xfz android-sdk_r22.3-linux.tgz
- export ANDROID_HOME=$PWD/android-sdk-linux
- export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
- echo "y" | android update sdk -u -f --filter platform-tools,build-tools-19.0.0,extra-android-support,android-19 1>/dev/null
- wget http://dl.google.com/android/ndk/android-ndk-r9b-linux-x86_64.tar.bz2
- tar xfj android-ndk-r9b-linux-x86_64.tar.bz2
- export NDK_HOME=$PWD/android-ndk-r9b
- export PATH=${PATH}:${NDK_HOME}

#   Build and check drops
script:
- ./autogen.sh && ./configure && make check
- sudo make install && sudo ldconfig

#   Build Android app
- cd ./src/app
- android update project -p .
- ndk-build
- ant debug
