# edgenet drops

language: c

#   Build required ZeroMQ projects first
before_script:
- sudo apt-get -qq update
- sudo apt-get install uuid-dev

#   Android build tools
#   Install SDK
- sudo apt-get install libstdc++6:i386 libgcc1:i386 zlib1g:i386 libncurses5:i386 ant
- wget http://dl.google.com/android/android-sdk_r22.3-linux.tgz
- tar xfz android-sdk_r22.3-linux.tgz
- export ANDROID_HOME=$PWD/android-sdk-linux
- export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
- echo "y" | android update sdk -u -f --filter platform-tools,build-tools-19.0.0,extra-android-support,android-19 1>/dev/null
#   Install NDK
- wget http://dl.google.com/android/ndk/android-ndk-r9b-linux-x86_64.tar.bz2
- tar xfj android-ndk-r9b-linux-x86_64.tar.bz2
- export NDK_HOME=$PWD/android-ndk-r9b
- export PATH=${PATH}:${NDK_HOME}
- $NDK_HOME/build/tools/make-standalone-toolchain.sh --platform=android-19 --install-dir=$PWD/toolchain
- export TOOLCHAIN=$PWD/toolchain

#   Build and check drops
script:
- cd builds/android
- ./update.sh && ./build.sh
- cd ../..

#   Build Android app
- cd src/app
- android update project -p . && ndk-build && ant debug
